#ifndef _LIBPLATFORM_EXPORT_H_
#define _LIBPLATFORM_EXPORT_H_

#include "TypeDefine.h"

enum PLATFORM_ID {
  PLATFORM_ID_UNINOWN = 0,
  PLATFORM_ID_FILESYSTEM,
  PLATFORM_ID_FILEMAP,
  PLATFORM_ID_DIRBROWSER,
  PLATFORM_ID_FILESTREAM,
  PLATFORM_ID_FILETARGET,
  PLATFORM_ID_MEMSTREAM,
  PLATFORM_ID_MEMTARGET,
  PLATFORM_ID_MODULE,
};

class IObject;

int libplatform_createInstance(IN PLATFORM_ID id, OUT IObject** object);

#endif
